app = "spar-agent-demo"
primary_region = "iad"

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "3000"
  WORKSPACE_PATH = "/workspace"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = "suspend"
  auto_start_machines = true
  min_machines_running = 0
  max_machines = 1

[[vm]]
  size = "shared-cpu-2x"
  memory = "1024"
