name: Build and Release Spar Binaries

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - os: ubuntu-latest
            target: linux-x64
            outfile: spar
          - os: macos-latest
            target: darwin-x64
            outfile: spar
          - os: windows-latest
            target: windows-x64
            outfile: spar.exe
    steps:
    - uses: actions/checkout@v4

    - name: Setup Bun
      uses: oven-sh/setup-bun@v2
      with:
        bun-version: latest

    - name: Install dependencies
      run: bun install

    - name: Build binary`
      run: bun build --compile --minify --sourcemap index.ts --outfile dist/${{ matrix.outfile }}

    - name: Upload binary artifact
      uses: actions/upload-artifact@v4
      with:
        name: spar-${{ matrix.os }}
        path: dist/${{ matrix.outfile }}

  release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Download artifacts
      uses: actions/download-artifact@v4
      with:
        pattern: spar-*

    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        files: |
          spar-ubuntu-latest/spar
          spar-macos-latest/spar
          spar-windows-latest/spar.exe
        draft: false
        prerelease: false